# Generated by Django 5.0 on 2026-02-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('tipo_negocio', models.CharField(choices=[('RESTAURANTE', 'Restaurante'), ('CAFETERIA', 'Cafetería'), ('CARRO', 'Carro'), ('FOOD_TRUCK', 'Food Truck')], max_length=20)),
                ('margen', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
