# Generated by Django 5.0 on 2026-04-06 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='negocio',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Negocio', 'verbose_name_plural': 'Negocios'},
        ),
        migrations.AlterField(
            model_name='negocio',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del negocio'),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=177, verbose_name='Nombre del categoria')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios.negocio', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('negocio', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios.negocio', verbose_name='clientes')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del insumo')),
                ('unidad_medida', models.CharField(choices=[('KG', 'Kilogramo'), ('LT', 'litro'), ('GR', 'Gramo'), ('ML', 'Mililitro'), ('UN', 'Unidad')], default='UN', max_length=3)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='negocios.negocio')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('negocio', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('stock_reservado', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('insumo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventario', to='negocios.insumo')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('MERMA', 'Merma'), ('AJUSTE', 'Ajuste Manual'), ('RESERVA', 'Reserva Evento'), ('LIBERACION', 'Liberacion Reserva')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_inventarios', to='negocios.insumo')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('P', 'Producto'), ('S', 'Servicio')], default='P', max_length=1)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del producto')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='negocios.categoria', verbose_name='Categoria')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='negocios.negocio')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RecetaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_en', to='negocios.insumo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='negocios.producto')),
            ],
            options={
                'verbose_name': 'Receta producto',
                'verbose_name_plural': 'Receta productos',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('producto', 'insumo')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='insumos',
            field=models.ManyToManyField(related_name='productos', through='negocios.RecetaProducto', to='negocios.insumo'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total de venta')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de venta')),
                ('pagado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='negocios.cliente')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocios.negocio', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('negocio', 'nombre')},
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='negocios.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='negocios.venta')),
            ],
            options={
                'verbose_name': 'Detalle Venta',
                'verbose_name_plural': 'Detalles Ventas',
                'unique_together': {('venta', 'producto')},
            },
        ),
    ]
