# Generated by Django 5.0 on 2026-04-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0002_alter_negocio_options_alter_negocio_nombre_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='stock',
            field=models.FloatField(default=0),
        ),
    ]
