# Generated by Django 5.0 on 2026-04-07 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0003_insumo_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuenciaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_numero', models.IntegerField(default=0)),
                ('negocio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secuencia_venta', to='negocios.negocio')),
            ],
        ),
    ]
