# Generated by Django 5.2.15 on 2026-06-10 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0004_secuenciaventa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AddField(
            model_name='negocio',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='negocios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=177, verbose_name='Nombre de la categoría'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='negocios.negocio'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(choices=[('KG', 'Kilogramo'), ('LT', 'Litro'), ('GR', 'Gramo'), ('ML', 'Mililitro'), ('UN', 'Unidad')], default='UN', max_length=3),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('MERMA', 'Merma'), ('AJUSTE', 'Ajuste Manual'), ('RESERVA', 'Reserva Evento'), ('LIBERACION', 'Liberación Reserva')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='negocios.categoria', verbose_name='Categoría'),
        ),
    ]
