# Generated by Django 5.2.15 on 2026-07-18 22:15
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('negocios', '0008_alter_cliente_usuario_alter_cliente_unique_together'),
    ]
    operations = [
        migrations.AddField(
            model_name='pedido',
            name='token_publico',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=False, null=True),
        ),
    ]