# Generated by Django 5.2.15 on 2026-07-18 22:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0010_asignar_tokens_publicos_unicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='token_publico',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
